import React, { useState } from "react";
import { MedicalImage, Annotation, WorkspaceMode } from "../../types";
import { StatusBadge, ModalityBadge } from "../common/Badge";
import { Button } from "../common/Button";
import { Modal } from "../common/Modal";
import {
  FileText,
  ShieldCheck,
  Tag,
  Sparkles,
  Eye,
  Info,
  CheckCircle2,
  XCircle,
  Edit3,
  Save,
  X,
  AlertTriangle,
  HelpCircle,
} from "lucide-react";

interface ImageMetadataPanelProps {
  image: MedicalImage;
  annotation: Annotation | null;
  mode: WorkspaceMode;
  isOverlayVisible: boolean;
  onAccept?: () => void;
  onReject?: (reason: string) => void;
  onEdit?: () => void;
  onCancelEdit?: () => void;
  onSaveEdit?: () => void;
  onCancelManual?: () => void;
  onSaveManual?: () => void;
  isProcessing?: boolean;
  isSaving?: boolean;
  liveCoveragePercent?: number;
  isMaskEmpty?: boolean;
}

export const ImageMetadataPanel: React.FC<ImageMetadataPanelProps> = ({
  image,
  annotation,
  mode,
  isOverlayVisible,
  onAccept,
  onReject,
  onEdit,
  onCancelEdit,
  onSaveEdit,
  onCancelManual,
  onSaveManual,
  isProcessing = false,
  isSaving = false,
  liveCoveragePercent,
  isMaskEmpty = false,
}) => {
  const [isAcceptModalOpen, setIsAcceptModalOpen] = useState(false);
  const [isRejectModalOpen, setIsRejectModalOpen] = useState(false);
  const [rejectReason, setRejectReason] = useState("");

  const handleConfirmAccept = () => {
    setIsAcceptModalOpen(false);
    onAccept?.();
  };

  const handleConfirmReject = () => {
    setIsRejectModalOpen(false);
    onReject?.(rejectReason);
    setRejectReason("");
  };

  const hasAiData = Boolean(
    annotation && (annotation.source === "ai" || annotation.source === "ai-edited" || annotation.maximumOutputScore !== undefined)
  );

  const displayCoverage =
    liveCoveragePercent !== undefined
      ? liveCoveragePercent
      : annotation?.maskCoveragePercent !== undefined
      ? annotation.maskCoveragePercent
      : 0;

  const findingText =
    annotation?.finding === "possible-region-detected" || (annotation?.shapes && annotation.shapes.length > 0)
      ? "Possible pneumothorax region detected"
      : "No pneumothorax region detected by AI";

  // Determine whether sidebar has actions for the current mode
  const showSidebarActions =
    mode === "ai-review" || mode === "ai-edit" || mode === "manual-edit";

  return (
    <div className="bg-white border-l border-slate-200 w-80 md:w-96 flex flex-col h-full overflow-hidden text-xs text-slate-700 select-none flex-shrink-0">
      {/* 1. Compact Image Heading */}
      <div className="p-3.5 bg-slate-50 border-b border-slate-200 flex-shrink-0 space-y-1.5">
        <div className="flex items-center justify-between">
          <ModalityBadge modality={image.modality} />
          <StatusBadge status={image.status} size="sm" />
        </div>
        <h3 className="text-sm font-bold text-slate-900 truncate" title={image.name}>
          {image.name}
        </h3>
      </div>

      {/* 2. Scrollable Information Area */}
      <div className="flex-1 overflow-y-auto overflow-x-hidden p-3.5 space-y-4 divide-y divide-slate-100">
        {/* AI Finding & Metrics Section */}
        {hasAiData ? (
          <div className="space-y-3 pt-1 first:pt-0">
            {/* Finding Banner */}
            <div
              className={`p-3 rounded-lg border flex items-start gap-2.5 ${
                findingText.includes("Possible")
                  ? "bg-cyan-50/80 border-cyan-200 text-cyan-950"
                  : "bg-slate-50 border-slate-200 text-slate-900"
              }`}
            >
              <Sparkles className="w-4 h-4 text-cyan-600 flex-shrink-0 mt-0.5" />
              <div className="space-y-0.5 flex-1 min-w-0">
                <div className="flex items-center justify-between">
                  <span className="font-bold text-xs">{findingText}</span>
                  <span className="text-[10px] font-semibold uppercase px-1.5 py-0.2 bg-cyan-100 text-cyan-800 rounded border border-cyan-300">
                    Cyan Overlay
                  </span>
                </div>
                <p className="text-[11px] text-slate-600 leading-tight">
                  {findingText.includes("Possible")
                    ? "Candidate pneumothorax contours generated by segmentation model."
                    : "Model detected no abnormal candidate areas at operational threshold."}
                </p>
              </div>
            </div>

            {/* Metrics Breakdown */}
            <div className="bg-slate-50 p-2.5 rounded-lg border border-slate-200 space-y-1.5 text-[11px]">
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Suggested Regions:</span>
                <span className="font-mono font-bold text-slate-900">{annotation?.shapes.length || 0}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Mask Coverage:</span>
                <span className="font-mono font-bold text-slate-900">{displayCoverage}%</span>
              </div>
              {annotation?.maximumOutputScore !== undefined && (
                <div className="flex justify-between items-center">
                  <span className="text-slate-500 flex items-center gap-1">
                    <span>Max Output Score:</span>
                    <span
                      className="cursor-help text-slate-400 hover:text-slate-600"
                      title="Model output score is not diagnostic confidence."
                    >
                      <HelpCircle className="w-3 h-3" />
                    </span>
                  </span>
                  <span className="font-mono text-teal-700 font-bold">{annotation.maximumOutputScore}</span>
                </div>
              )}
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Review Status:</span>
                <span className="capitalize font-medium text-slate-800">{image.status.replace("-", " ")}</span>
              </div>
              <div className="flex justify-between items-center">
                <span className="text-slate-500">Overlay Display:</span>
                <span className="flex items-center gap-1 font-medium text-slate-700">
                  <Eye className="w-3 h-3 text-slate-400" />
                  <span>{isOverlayVisible ? "Visible" : "Hidden"}</span>
                </span>
              </div>

              {/* Reference-based metrics */}
              {annotation?.referenceMetrics ? (
                <div className="p-2 bg-emerald-50 rounded border border-emerald-200 mt-2 space-y-1">
                  <span className="text-[10px] font-bold text-emerald-900 block">AI-to-Reference Agreement:</span>
                  <div className="grid grid-cols-2 gap-1 text-[10px] font-mono text-emerald-800">
                    <span>Dice: {annotation.referenceMetrics.dice}</span>
                    <span>IoU: {annotation.referenceMetrics.iou}</span>
                    <span>Precision: {annotation.referenceMetrics.precision}</span>
                    <span>Recall: {annotation.referenceMetrics.recall}</span>
                  </div>
                </div>
              ) : (
                <div className="flex items-center gap-1 text-slate-500 text-[10px] pt-1 border-t border-slate-200">
                  <Info className="w-3 h-3 text-slate-400 flex-shrink-0" />
                  <span>Reference-based metrics: Not available</span>
                </div>
              )}
            </div>

            {/* Human Review Required Notice */}
            <div className="p-2.5 bg-amber-50/80 rounded-lg border border-amber-200 text-amber-900 flex items-start gap-2 text-[11px] leading-tight">
              <AlertTriangle className="w-3.5 h-3.5 text-amber-700 flex-shrink-0 mt-0.5" />
              <span>
                <strong>Human Review Required:</strong> AI output is an investigational proposal and must be verified by a qualified clinician.
              </span>
            </div>

            {/* Empty Annotation Notice during edit */}
            {(mode === "ai-edit" || mode === "manual-edit") && isMaskEmpty && (
              <div className="p-2 bg-rose-50 rounded-lg border border-rose-200 text-rose-800 text-[11px] font-medium">
                The annotation is currently empty (all pixels erased).
              </div>
            )}
          </div>
        ) : (
          <div className="pt-2">
            <p className="text-slate-500 italic text-[11px] leading-relaxed">
              No AI suggestion generated yet for this image. Click "Request AI Suggestion" in the top header to run automatic candidate segmentation.
            </p>
          </div>
        )}

        {/* Active Annotation Summary */}
        <div className="pt-3 space-y-2">
          <h4 className="font-semibold text-slate-900 text-xs uppercase tracking-wider flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-teal-700" />
            <span>Annotation Summary</span>
          </h4>

          <div className="space-y-1.5 text-[11px]">
            <div className="flex justify-between">
              <span className="text-slate-500">Source:</span>
              <span className="font-semibold uppercase text-slate-800">
                {annotation?.source === "ai"
                  ? "AI Suggestion"
                  : annotation?.source === "ai-edited"
                  ? "AI Edited"
                  : annotation?.source === "manual"
                  ? "Manual"
                  : "None"}
              </span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Active Shapes:</span>
              <span className="font-mono text-slate-800">{annotation?.shapes.length || 0}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Annotator:</span>
              <span className="font-medium text-slate-800">{image.annotator || "Unassigned"}</span>
            </div>
          </div>
        </div>

        {/* Image Details */}
        <div className="pt-3 space-y-2">
          <h4 className="font-semibold text-slate-900 text-xs uppercase tracking-wider flex items-center gap-1.5">
            <FileText className="w-3.5 h-3.5 text-teal-700" />
            <span>Image Details</span>
          </h4>

          <div className="space-y-1.5 text-[11px]">
            <div className="flex justify-between">
              <span className="text-slate-500">Dimensions:</span>
              <span className="font-mono text-slate-800">{image.width} × {image.height} px</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">File Type:</span>
              <span className="font-mono uppercase text-slate-800">{image.fileType}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">File Size:</span>
              <span className="text-slate-800">{image.fileSizeFormatted || "2.4 MB"}</span>
            </div>
            <div className="flex justify-between">
              <span className="text-slate-500">Added:</span>
              <span className="text-slate-800">{new Date(image.uploadedAt).toLocaleDateString()}</span>
            </div>
          </div>
        </div>

        {/* DICOM Header Tags (if applicable) */}
        {image.dicomMetadata && (
          <div className="pt-3 space-y-2">
            <h4 className="font-semibold text-slate-900 text-xs uppercase tracking-wider flex items-center gap-1.5">
              <Tag className="w-3.5 h-3.5 text-teal-700" />
              <span>DICOM Metadata</span>
            </h4>

            <div className="bg-slate-50 p-2 rounded border border-slate-200 font-mono text-[10px] space-y-1 text-slate-700">
              <div><span className="text-slate-400">Position:</span> {image.dicomMetadata.viewPosition || "PA ERECT"}</div>
              <div><span className="text-slate-400">Photometric:</span> {image.dicomMetadata.photometricInterpretation || "MONOCHROME2"}</div>
              <div><span className="text-slate-400">kVp:</span> {image.dicomMetadata.kvp || "120 kV"}</div>
            </div>
          </div>
        )}
      </div>

      {/* 3. Fixed Review Actions at Bottom of Sidebar (Rendered ONLY when mode requires sidebar actions) */}
      {showSidebarActions && (
        <div className="p-3 bg-white border-t border-slate-200 flex-shrink-0 z-20 space-y-2">
          {/* MODE: AI REVIEW -> Reject / Edit / Accept */}
          {mode === "ai-review" && (
            <div className="space-y-2">
              <Button
                variant="teal"
                size="sm"
                onClick={() => setIsAcceptModalOpen(true)}
                disabled={isProcessing || isSaving}
                className="w-full justify-center"
                leftIcon={<CheckCircle2 className="w-4 h-4" />}
              >
                Accept Suggestion
              </Button>
              <div className="grid grid-cols-2 gap-2">
                <Button
                  variant="secondary"
                  size="sm"
                  onClick={onEdit}
                  disabled={isProcessing || isSaving}
                  className="justify-center"
                  leftIcon={<Edit3 className="w-3.5 h-3.5 text-slate-700" />}
                >
                  Edit
                </Button>
                <Button
                  variant="danger"
                  size="sm"
                  onClick={() => setIsRejectModalOpen(true)}
                  disabled={isProcessing || isSaving}
                  className="justify-center"
                  leftIcon={<XCircle className="w-3.5 h-3.5" />}
                >
                  Reject
                </Button>
              </div>
            </div>
          )}

          {/* MODE: AI EDIT -> Cancel Editing / Save Edited Annotation */}
          {mode === "ai-edit" && (
            <div className="space-y-2">
              <Button
                variant="teal"
                size="sm"
                onClick={onSaveEdit}
                isLoading={isSaving}
                className="w-full justify-center"
                leftIcon={<Save className="w-4 h-4" />}
              >
                Save Edited Annotation
              </Button>
              <Button
                variant="secondary"
                size="sm"
                onClick={onCancelEdit}
                disabled={isSaving}
                className="w-full justify-center text-slate-600"
                leftIcon={<X className="w-3.5 h-3.5" />}
              >
                Cancel Editing
              </Button>
            </div>
          )}

          {/* MODE: MANUAL EDIT -> Cancel / Save Annotation */}
          {mode === "manual-edit" && (
            <div className="space-y-2">
              <Button
                variant="primary"
                size="sm"
                onClick={onSaveManual}
                isLoading={isSaving}
                className="w-full justify-center"
                leftIcon={<Save className="w-4 h-4" />}
              >
                Save Annotation
              </Button>
              <Button
                variant="secondary"
                size="sm"
                onClick={onCancelManual}
                disabled={isSaving}
                className="w-full justify-center text-slate-600"
                leftIcon={<X className="w-3.5 h-3.5" />}
              >
                Cancel
              </Button>
            </div>
          )}
        </div>
      )}

      {/* Confirmation Modal: Accept Suggestion */}
      <Modal
        isOpen={isAcceptModalOpen}
        onClose={() => setIsAcceptModalOpen(false)}
        title="Accept AI Suggestion"
        subtitle="Confirm and finalize this AI segmentation proposal as expert ground truth."
        footer={
          <>
            <Button variant="secondary" onClick={() => setIsAcceptModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="teal" onClick={handleConfirmAccept} leftIcon={<CheckCircle2 className="w-4 h-4" />}>
              Confirm & Finalize
            </Button>
          </>
        }
      >
        <div className="space-y-2 text-xs text-slate-700">
          <p>
            By accepting, you confirm that you have reviewed the AI-suggested candidate contours and approve them as clinically accurate.
          </p>
          <div className="p-2 bg-slate-50 border border-slate-200 rounded text-[11px] text-slate-600">
            • Status will change to <strong>Finalized</strong>.<br />
            • Overlay color will convert to <strong>Green</strong>.<br />
            • Your user credentials will be recorded in the audit history.
          </div>
        </div>
      </Modal>

      {/* Confirmation Modal: Reject Suggestion */}
      <Modal
        isOpen={isRejectModalOpen}
        onClose={() => setIsRejectModalOpen(false)}
        title="Reject AI Suggestion"
        subtitle="Discard the candidate segmentation mask and restore this image to unannotated status."
        footer={
          <>
            <Button variant="secondary" onClick={() => setIsRejectModalOpen(false)}>
              Cancel
            </Button>
            <Button variant="danger" onClick={handleConfirmReject} leftIcon={<XCircle className="w-4 h-4" />}>
              Reject & Discard Mask
            </Button>
          </>
        }
      >
        <div className="space-y-3 text-xs text-slate-700">
          <p>The proposed AI mask will be discarded and the study will return to Unannotated status.</p>
          <div>
            <label className="block font-medium text-slate-800 mb-1 text-[11px]">
              Rejection Reason (Optional):
            </label>
            <textarea
              value={rejectReason}
              onChange={(e) => setRejectReason(e.target.value)}
              placeholder="e.g., False positive apical contour; artifact mistaken for pleural line..."
              className="w-full text-xs p-2 border border-slate-300 rounded-lg focus:ring-1 focus:ring-red-500 focus:border-red-500"
              rows={2}
            />
          </div>
        </div>
      </Modal>
    </div>
  );
};
